### ISSUE TITLE
Forward references break give a confusing error

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#121]
```yaml
global:
  prefix: projected_tucker
  sequences_file: bonsai/knn_reference.fasta
bert_embed:
  type: embed
  protocol: prottrans_bert_bfd
  reduce: true
  discard_per_amino_acid_embeddings: true
visualize_bert:
  type: visualize
  protocol: plotly
  depends_on: umap_tucker
  n_components: 2
umap_tucker:
  type: project
  protocol: umap
  depends_on: bert_embed
```

This (correctly) fails, but instead of triggering the `"Stage {} depends on {}, but dependency not found in config."` error, it complains about a missing parameter
