### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#148]
![image](https://user-images.githubusercontent.com/54856692/126423893-ad37fc44-3a87-44f0-9781-4c2c82682580.png)

Please give me some guideline

**Comment by konstin** [comment]
Hi, can you please post your `config.yml`?

**Comment by gerdos** [comment]
I have the same error when I try to do the deeplock protocol form the article. My config.yml looks like this:

```global:

sequences_file: deeploc_data.fasta

prefix: deeploc_embeddings

simple_remapping: True

 

prottrans_bert_embeddings:

type: embed

protocol: prottrans_bert_bfd

reduce: True
```

**Comment by gerdos** [comment]
I think I was able to solve it. So the config file needs the indentation. The article correctly shows the indentation on the PDF doc, but on the main site it does not have indentation. 

Correct config.yml:

```
global:
        sequences_file: deeploc_data.fasta
        prefix: deeploc_embeddings
        simple_remapping: True

prottrans_bert_embeddings:
        type: embed
        protocol: prottrans_bert_bfd
        reduce: True
```
